### ISSUE TITLE
Camera does not follow the user properly in NavigationViewController

### ISSUE THREAD

**Issue by ianthetechie** [maplibre/maplibre-navigation-ios#1]
I am trying to get this project working in a non-Mapbox environment and for some reason the camera is not properly following the user. My understanding is that this is supposed to happen automatically.

To elaborate a bit on what non-Mapbox looks like, we are using OpenMapTiles-derived tiles (Stadia Maps) in place of Mapbox map tiles, and are constructing the `Route` directly from an OSRM JSON response (in this case, generated by the Stadia Maps Valhalla API; to save the trouble for those not familiar, the Mapbox Directions API v5 only adds a few minor things, mostly related to voice navigation, to the OSRM response format, and these are optional).

### Steps to Trigger Behavior

1. Create a `Route` (in this case, parsed from an OSRM response)
2. Create a `Style` pointing to a Stadia Maps URL (I suspect any non-Mapbox URL will do; ex: MapTiler if you prefer)
3. Create a `SimulatedLocationManager` with the route and set a speed multiplier of 5 so you aren't waiting all day ;)
4. Create a `NavigationViewController` using the route, style and simulated location manager from above
5. Present the view controller

### Link to Minimal Reproducible Example

https://github.com/ianthetechie/maplibre-ios-camera-mre. Two notes on this. 1) you will need a (free) Stadia Maps API key, which obviously isn't published (edit Config.swift). 2) I'm referencing a fork of maplibre-navigation-ios to remove a few mapbox dependencies, but the issue appears with the official release as well.

### Expected Behavior

The user "puck" should move along the route line, the camera heading/bearing should adjust to the user, and he camera should move "forward" along with the user puck.

### Actual Behavior

The user puck moves along the route line. While the camera DOES change in some manner (bearing/heading only), it never actually follows the user, or even fully changes bearing to point toward the user.

### Screenshots (if applicable)

https://user-images.githubusercontent.com/2140440/218034990-562ece68-373f-4540-a513-1e4405de1b26.MP4

I cut the video off a bit early but it never catches up to the user or pans the correct direction.

### Version(s) affected

- Platform: iOS
- OS version: 16.3
- Device type: iPhone 13 Mini
- Emulator/ Simulator: no
- Development OS: macOS Ventura 13.1
- maplibre-navigation-ios Version 1.0.7
- MapLibre GL version 5.12.2

### Additional context

I forked the repo because the current road info was not showing and I was getting console errors about the `mapbox://` URL scheme not being supported. Is it possible that the dependency on the street styles is responsible in some way? I'm poking around `RouteMapViewController` as this seems to be a likely spot for camera manipulation but it's going to take me a bit to parse it all.

**Comment by mindthefish** [comment]
I can confirm the issue. What is strange is that the position on the map is set correctly again when you bring the app to the background and then back to the foreground. I'll keep trying, but haven't gotten deep enough into the SDK yet.

@ianthetechie: Thanks for your navigation example. It helped me a lot to include my own route.

**Comment by olkiz** [comment]
I found, that if removing the edgePaddings argument from the setCamera in NavigationMapView::updateCourseTracking, the camera starts to follow, but there is no offset (the puck is on the center of the camera). Maybe there is a bug in MGLMapView setCamera?

**Comment by olkiz** [comment]
I found that something was changed with edgePadding in https://github.com/maplibre/maplibre-gl-native/issues/171. Anyway I think we need to open issue in maplibre

**Comment by olkiz** [comment]
I've opened an issue in maplibre gl native https://github.com/maplibre/maplibre-gl-native/issues/958

**Comment by imranMnts** [comment]
@frederoni can someone please have a look at this issue, or at least give a status?

**Comment by olkiz** [comment]
Seems the solution is to set content insets for maplibre and to remove from function mapView.setCamera edgePadding argument. So was early in mapbox if to see git history.

**Comment by georgbachmann** [comment]
Is there any news on this? In my case the camera is just positioning itself very strange, so that the user-puck is always on the very low bottom... hard to see...
Is this project here still alive?

**Comment by georgbachmann** [comment]
@wipfli currently I would not have any time at all. And I also don' really use the navigation part all that much. It's just a smaller part of an app I am working on...

**Comment by torrswanson** [comment]
Seems to be a bug in the left and right values of the MGLMapView setCameta(... edgePadding: UIEdgeInsets ...)` when they aren't 0

I've removed updateCourseTracking in layoutSubviews when not using .zero for edgePadding in the setCamera(..).

I'm using let padding = UIEdgeInsets(top: point.y, left: 0.0, bottom: bounds.height - point.y, right: 0.0). Specifically, setting 0 values for left and right. This means not using the self.cameraEdgeInsets that is propsed in this pull request and leaving the padding value based off the userAnchorPoint that itself can be based off a delegate method. I'd rather leave top and bottom values as-is. There should be a really really good reason to get rid of using userAnchorPoint for this PR to be approved as the top and bottom values at runtime are different as shown below.

On my iPhone 8, these are the values i'm getting at runtime:
self.cameraEdgeInsets is UIEdgeInsets(top: 597.6, left: 0.0, bottom: 125.39999999999998, right: 0.0)
padding is UIEdgeInsets(top: 501.6, left: 0.0, bottom: 125.39999999999998, right: 0.0)

I'm not using contentInsets on the NavigationMapView because it alters the Attribution marks.

**Comment by boldtrn** [comment]
Please feel free to provide a PR @torrswanson 👍
