### ISSUE TITLE
Compiled module was created by a different version of the compiler

### ISSUE THREAD

**Issue by Djibs** [maplibre/maplibre-navigation-ios#14]
Hello,

When I try to compile the app in the simulator I get this error. At the beginning of November I was on the project, everything was working, but now it's no longer working. I have the latest version of xcode (15.1) but there is. 2 months it was version 15.0.1

I did a clean builder and deleted the derived data, but it doesn't change anything.

I also tried to do carthage update

### Screenshots (if applicable)

![Capture ecran 2023-12-29 à 15 19 41](https://github.com/maplibre/maplibre-navigation-ios/assets/1236842/33968894-70ff-4c1b-b8bc-df6b6824bf1c)

![d](https://github.com/maplibre/maplibre-navigation-ios/assets/1236842/7a555b1a-2593-4177-a85a-db5cbfe2fee9)

### Version(s) affected

- Platform:iOS
- OS version: 17.2
- Device type: Iphone 15 Pro
- Emulator/ Simulator: yes
- Development OS: macOS 14.2
- maplibre-navigation-ios Version 1.0.6
- MapLibre GL version 5.12.2

### Additional context
Xcode : 15.1

**Comment by boldtrn** [comment]
I think the MapboxDirections are currently a bit troublesome, I just commented about this on another issue here: https://github.com/maplibre/maplibre-navigation-ios/issues/10#issuecomment-1872160631

The current state on main works on my machine. Have you tried running `carthage update --platform iOS --use-xcframeworks` (note the two arguments, you ran the command without the arguments).

**Comment by Djibs** [comment]
thank you for your reply

yes, buil failed:


`Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/xxxx/Documents/FoxyPark/Carthage/Checkouts/mapbox-events-ios/MapboxMobileEvents.xcodeproj -scheme MapboxMobileMetrics -configuration Release -derivedDataPath /Users/xxxx/Library/Caches/org.carthage.CarthageKit/DerivedData/15.1_15C65/mapbox-events-ios/v0.10.2 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive VALIDATE_WORKSPACE=NO -archivePath /var/folders/wg/3_gmmq1j2hg4lwd0mtx3f8400000gn/T/mapbox-events-ios SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/xxxx/Documents/FoxyPark/Carthage/Checkouts/mapbox-events-ios)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/wg/3_gmmq1j2hg4lwd0mtx3f8400000gn/T/carthage-xcodebuild.rpXz4g.log`

**Comment by boldtrn** [comment]
> maplibre-navigation-ios Version 1.0.6

Are you really using 1.0.6? Could you try the current version on main. I just rebuild the latest version from main and it works on my machine.

You could try to delete the derived data folder:

> /Users/xxxx/Library/Caches/org.carthage.CarthageKit/DerivedData/

**Comment by Djibs** [comment]
> Are you really using 1.0.6? Could you try the current version on main. I just rebuild the latest version from main and it works on my machine.

in the tutorial it is indicated to install this version

**Comment by Djibs** [comment]
It is working thank you

**Comment by boldtrn** [comment]
Thanks for the feedback, just for anyone looking for help on this in the future, could you document your solution and close the issue?

**Comment by Djibs** [comment]
The tutorial "Getting Started" is not up to date, the command should be changed.

In  **5.Add dependencies to Cartfile**

replace

`github "maplibre/maplibre-navigation-ios" ~> 1.0.6`

by

`github "maplibre/maplibre-navigation-ios" ~> 2.0.0`

**Comment by boldtrn** [comment]
Ah ok got it, if you like to improve the tutorial, would you mind to create a PR?

**Comment by Djibs** [comment]
it is done.

thank you
