### ISSUE TITLE
Merge rules

### ISSUE THREAD

**Issue by wipfli** [maplibre/maplibre-navigation-ios#17]
Normally we do reviews and only merge pull requests with at least one approval.

But since this repo is a bit outdated, @boldtrn  will do some clean up and merge without requiring reviews.

@boldtrn please close this issue once we go back to normal mode reviews. 

Thanks in advance and happy 2024!

**Comment by boldtrn** [comment]
Thanks for the trust @wipfli and happy 2024 🎉

**Comment by boldtrn** [comment]
I will close this for now as the repo has become way more active by now.
