### ISSUE TITLE
Update to Maplibre 6.x

### ISSUE THREAD

**Issue by boldtrn** [maplibre/maplibre-navigation-ios#20]
We should update to Maplibre 6 with metal - https://github.com/maplibre/maplibre-native/releases

If anyone wants to work on this, please let us know in this issue.

**Comment by mindthefish** [comment]
I gave it a shot a couple of weeks ago with a pre-release of 6.0, but ran into too many loose ends. Still, I can try to support here.

**Comment by boldtrn** [comment]
Thanks, sounds good :). If you do remember the issues, maybe we can document them here already, so we have an overview of the challenges. 

If you feel like it, it might make sense to open a draft PR so we can track the current state and go from there?

**Comment by mindthefish** [comment]
https://github.com/maplibre/maplibre-navigation-ios/pull/23 is open, happy about reviewers.

**Comment by boldtrn** [comment]
Thanks a lot for providing your PR @mindthefish 👍
