### ISSUE TITLE
SPM compatibility

### ISSUE THREAD

**Issue by Djibs** [maplibre/maplibre-navigation-ios#22]
## Motivation

To facilitate installation and knowing that native MapLibre is compatible with SPM (swift package manager), would it be possible to make MapLibre Navigation compatible with SPM?

**Comment by boldtrn** [comment]
I would love to see this 👍. PRs are welcome.

**Comment by mindthefish** [comment]
This would be great. As far as I know all dependencies need to support this too. I could not find a `Package.swift` inside the https://github.com/flitsmeister/mapbox-directions-swift repository though.

**Comment by Djibs** [comment]
an update for SPM support is pending for mapbox-directions : https://github.com/flitsmeister/mapbox-directions-swift/pull/5#commits-pushed-888dc58

**Comment by mindthefish** [comment]
https://github.com/flitsmeister/mapbox-directions-swift/pull/5#commits-pushed-888dc58 is merged.

**Comment by boldtrn** [comment]
Awesome, so at the very least we could update the dependency 👍

**Comment by iamalexantonov** [comment]
Hey, I know that the SPM support was recently merged. But when can we expect a new release?

**Comment by boldtrn** [comment]
Soonish, please feel free to use the latest commit form the main branch, this already works. Please test it and feel free to open a PR if something is missing.
