### ISSUE TITLE
dyld Library not loaded: @rpath/Mapbox.framework/Mapbox thrown by MapboxNavigation

### ISSUE THREAD

**Issue by BroodjeSteen** [maplibre/maplibre-navigation-ios#28]
Hello, I am building an application with React Native and I'm trying to build a custom component with the Maplibre Navigation SDK. The problem I'm having lies directly in the install of the additional frameworks downloaded with Carthage. Each of the downloaded frameworks works and the application loads after building, except when I add the MapboxNavigation framework to the "Frameworks, Libraries and Embedded Content" in XCode.

### Steps to Trigger Behavior
1. Follow install steps in README.md

### Expected Behavior
Application should load after install without using the SDK.

### Actual Behavior
Application throws error when loading the MapboxNavigation framework.

### Screenshots (if applicable)
![Screenshot 2024-02-22 at 16 26 15](https://github.com/maplibre/maplibre-navigation-ios/assets/103312360/e5f97539-0efc-4f19-81a9-5b977939ecd0)
![Screenshot 2024-02-22 at 16 30 44](https://github.com/maplibre/maplibre-navigation-ios/assets/103312360/717fd85d-22c3-4497-84c7-afe612d4c332)
These are the downloaded frameworks. Might I be missing a Mapbox.xcframework?

### Version(s) affected

- OS version: iOS 17.2
- Device type: iPhone 15 Pro
- Emulator/ Simulator: yes
- Development OS: macOS 14.1.1
- maplibre-navigation-ios Version 2.0.0
- MapLibre GL version 6.0.0

**Comment by boldtrn** [comment]
Once #24 is merged, we don't need Carthage anymore.

I would recommend to use the current master of this repository. That way you get access to the latest Maplibre version 6.

**Comment by BroodjeSteen** [comment]
I am using the current master. Might it be that I am using a too recent version of XCode so that the frameworks don't build right? I'm currently using XCode 15 though the release page of this repository says to use XCode 14.

**Comment by mindthefish** [comment]
Did you add MapLibre as SPM dependency like described in the step 4 in the [README](https://github.com/maplibre/maplibre-navigation-ios/blob/main/README.md)? This should add MapLibre the the Frameworks list of your application.

**Comment by BroodjeSteen** [comment]
I have followed all the steps from the README, I can also see that the SPM dependency works by importing MapLibre in a Swift file..

**Comment by michaelkirk** [comment]
Are you still having issues @BroodjeSteen? The SPM install instructions have been updated: https://github.com/maplibre/maplibre-navigation-ios?tab=readme-ov-file#getting-started

**Comment by BroodjeSteen** [comment]
Everything is working great since using the Swift Package. Thank you very much.
