### ISSUE TITLE
Update to latest Maplibre-Native

### ISSUE THREAD

**Issue by boldtrn** [maplibre/maplibre-navigation-ios#36]
Maplibre Native with the Metal renderer is moving fast right now, we should try to keep up. [ios-v6.3.2](https://github.com/maplibre/maplibre-native/releases/tag/ios-v6.3.2) was just released, updating should be pretty straight foward (I hope :))

**Comment by mindthefish** [comment]
I hope someone takes care of [#2228](https://github.com/maplibre/maplibre-native/issues/2228) soon, as this makes navigation pretty unusable in its current state. I will test version 6.3.2 by the beginning of next week at the latest.

**Comment by boldtrn** [comment]
Actually, my issue is somewhat invalid as the [Package.swift](https://github.com/maplibre/maplibre-navigation-ios/blob/main/Package.swift#L20) mentions from 6.0.0 and not exact. 

I agree @mindthefish it would be nice if the upstream issue would be resolved.
