### ISSUE TITLE
No such module 'MapboxDirections'

### ISSUE THREAD

**Issue by DavithkbY** [maplibre/maplibre-navigation-ios#38]
Just followed the getting started guide and when importing the demo ViewController code I get error:
No such module found
<img width="1065" alt="Screenshot 2024-04-16 at 23 36 14" src="https://github.com/maplibre/maplibre-navigation-ios/assets/71630103/03344975-3b36-4cef-847c-1bb34455642b">

**Comment by boldtrn** [comment]
Are you using the lastest version on the main branch? If yes, we recently switched to SPM, so no carthage is required any more. The getting started might be outdated (we should fix this).

**Comment by DavithkbY** [comment]
Yes am using the latest version. Please do update the getting started.

**Comment by boldtrn** [comment]
Actually I don't think you need to do anything else than just setting up SPM and to add this repo here as SPM package. This would be like:
![Screenshot 2024-04-19 at 16 57 30](https://github.com/maplibre/maplibre-navigation-ios/assets/1553525/41cb6589-6516-4987-a5d0-075c51d2e8ce)

The directions are a dependency of maplibre-navigation-ios and should be resolved when you resolve the package.

**Comment by berkayoruc** [comment]
I tried 6.0.0 and 6.4.0 versions but MapboxDirections module is missing. Any example or documentation about new versions?

**Comment by boldtrn** [comment]
The directions is referenced here: https://github.com/maplibre/maplibre-navigation-ios/blob/main/Package.swift#L18

**Comment by michaelkirk** [comment]
Install docs updated in #40.

A likely culprit for the confusion is forgetting to select your target during SPM installation. If you did forget that configuration, you should be able to recover by manually updating your target's "Build Phases" > "Link Binary with Libraries" and adding the "MapboxNavigation" library.

**Comment by berkayoruc** [comment]
I'm sure whoever writes an explanatory example about iOS navigation would do a great favor. I tried a few things but it still didn't work. Frameworks added from cartfile. ios 17.0 simulator XCode 15.0
<img width="935" alt="Screenshot 2024-05-14 at 00 24 06" src="https://github.com/maplibre/maplibre-navigation-ios/assets/22800134/ae34cf73-3157-4641-bc1e-fc14174d3ec4">
<img width="270" alt="Screenshot 2024-05-14 at 00 24 14" src="https://github.com/maplibre/maplibre-navigation-ios/assets/22800134/0302073a-e417-42a4-918f-4aceca5618e3">
<img width="514" alt="Screenshot 2024-05-14 at 00 25 19" src="https://github.com/maplibre/maplibre-navigation-ios/assets/22800134/24a43814-3ca3-4c52-925b-eb0710fc1252">

**Comment by michaelkirk** [comment]
Have you tried the Swift Package Manager instructions from https://github.com/maplibre/maplibre-navigation-ios/pull/40 ?

**Comment by berkayoruc** [comment]
If I use just SPM some libs not installed (liked MapboxNavigation)

**Comment by michaelkirk** [comment]
Can you share a screenshot of your left panel in xcode? SPM should install all the dependencies.On May 13, 2024, at 20:53, Berkay Oruç ***@***.***> wrote:﻿
If I use just SPM some libs not installed (liked MapboxNavigation)

**Comment by berkayoruc** [comment]
> Can you share a screenshot of your left panel in xcode? SPM should install all the dependencies.On May 13, 2024, at 20:53, Berkay Oruç ***@***.***> wrote:﻿ If I use just SPM some libs not installed (liked MapboxNavigation) —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

I was able to add the package easily thanks to the new documentation. Thank you
