### ISSUE TITLE
Feedback in EndOfRouteViewController goes nowhere.

### ISSUE THREAD

**Issue by michaelkirk** [maplibre/maplibre-navigation-ios#62]
## Motivation

The EndOfRouteViewController looks like this:
<img width="274" alt="Screenshot 2024-06-13 at 16 55 03" src="https://github.com/maplibre/maplibre-navigation-ios/assets/217057/ca15241e-5830-4c35-b9ec-284a66168696">

If you click on one of the stars, a text field appears:
<img width="274" alt="Screenshot 2024-06-13 at 16 55 09" src="https://github.com/maplibre/maplibre-navigation-ios/assets/217057/33c3df28-a75f-40c4-9dc5-ca4c53d1e023">

There's currently a couple serious issues with the EndOfRouteViewController (EORVC as the git log affectionately calls it) #57, #58, (plus one more crash I haven't filed yet due to an invalid animation curve during keyboard presentation). 

I've work around them all, but then I finally thought to ask: What is this all for? 

I'm not currently collecting these end-of-trip feeback anywhere (though I'd actually like to at some point). I wondered if there was some sort of pluggable feedback service? It turns out there was a long time ago in the mapbox days, but it was removed back in: https://github.com/flitsmeister/maplibre-navigation-ios/pull/1 . These controls seem like a non-functioning remnant of that system.

## Design Alternatives

1. Leave the EORVC but delete the feedback elements. User sees only the "You have arrived" / "End Navigation" elements. (this is my preferred alternative)

2. ...or Delete the EORVC altogether. MaplibreNavigation would only fire a delegate hook, and the implementor is expected to end the route and provide any UI.

3. ...or Keep the EORVC  with its rating/feedback elements, but make it easy to hide them. Return the value of the feedback fields to the delegate method when the user taps "End Navigation" so that the implementor can handle it. This is the most functional, pre-supposes that the implementer wants to collect exactly this information. **Update: I realize now the EORVC already does return the rating/comment in the delegate callback... they're just ignored by `func embedEndOfRoute()`**. I still think we should drop it and say if people want to collect feedback or whatever they'll need to BYO EORVC.

I think I prefer alternative 1 - keeping the EORVC, but deleting the feedback elements and making it possible for the implementor to extend/replace this view.

I prefer this approach because I think it is coherent to present some kind of "You're Done!" state  arrives rather than leaving them in perpetual routing purgatory (and potentially re-reouting them if they subsequently wander).

I do think it's likely that people will want the ability to customize this UI (for example, I actually do want to collect feedback on my routing, but with different UI). I still think it's worthwhile to present some kind of basic UI. By presenting people with a default, that gets them a head start on a coherent navigation flow and if they do want a custom view there, they now have a way to trace back from what they already see in the UI to the specific place in the code they need to change rather than exhaustively cocvering such and such delegate documentation.

**Comment by boldtrn** [comment]
Yes I think the whole end of route logic was only for Mapbox. 

Option (1) and (2) both sound fine to me. I don't have strong feelings about either option.
