### ISSUE TITLE
Distribution of application to testflight failed 

### ISSUE THREAD

**Issue by sunny0092** [maplibre/maplibre-navigation-ios#9]
I run the virtual device, the real device runs fine, but when I build the application to upload to testlight, I get the error below. Can anyone help me with the same problem?

<img width="391" alt="Screenshot 2023-11-01 at 15 34 16" src="https://github.com/maplibre/maplibre-navigation-ios/assets/15792841/94895cc6-0bf9-4dcc-bab2-ffaf83b45acc">

<img width="744" alt="Screenshot 2023-11-01 at 10 57 55" src="https://github.com/maplibre/maplibre-navigation-ios/assets/15792841/73fe5dac-6719-4d97-b09f-5659f5ea902a">

<img width="531" alt="Screenshot 2023-11-01 at 11 05 26" src="https://github.com/maplibre/maplibre-navigation-ios/assets/15792841/a9fe0f1b-d30a-4364-8cc1-b53ff47721db">

I changed Embed & sign -> Do not Embed but running on a real mobile device doesn't work and gets an error

error: module importing failed: invalid pathname
dyld[17943]: Library not loaded: @rpath/MapboxNavigation.framework/MapboxNavigation

<img width="1707" alt="Screenshot 2023-11-01 at 11 08 54" src="https://github.com/maplibre/maplibre-navigation-ios/assets/15792841/ef15b258-bd15-4ecc-b5db-63c6bb7f3581">

**Comment by michaelkirk** [comment]
I have had no issues distributing through TestFlight. Are you still having issues?

**Comment by boldtrn** [comment]
Since we also had no issues and there hasn't been any more information, I'd say let's close this issue. @sunny0092 if you still see this issue, please feel free to reopen and if possible, provide more information. With the current version on main and SPM a lot should have changed already.
